(defun ugly-colors ()
  (interactive)
  (color-theme-install
   '(ugly-colors
     ((background-color . "#000000")
      (background-mode . light)
      (border-color . "#2e2e2e")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     (fringe ((t (:background "#2e2e2e"))))
     (mode-line ((t (:foreground "#aa55e2" :background "#292929"))))
     (region ((t (:background "#313131"))))
     (font-lock-builtin-face ((t (:foreground "#9f32c8"))))
     (font-lock-comment-face ((t (:foreground "#4a4a4a"))))
     (font-lock-function-name-face ((t (:foreground "#f64c57"))))
     (ruby-op-face ((t (:foreground "#E7FF4D"))))
     (font-lock-keyword-face ((t (:foreground "#915fd8"))))
     (font-lock-string-face ((t (:foreground "#7DD1BE"))))
     (font-lock-constant-face ((t (:foreground "#9490E8"))))
     (font-lock-type-face ((t (:foreground"#F772F3"))))
     (font-lock-variable-name-face ((t (:foreground "#d624ac"))))
     (minibuffer-prompt ((t (:foreground "#4f6d8c" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'ugly-colors)
