(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(auto-save-file-name-transforms (quote ((".*" "~/.emacs.d/autosaves/\\1" t))))
 '(backup-directory-alist (quote ((".*" . "~/.emacs.d/backups/"))))
 '(column-number-mode t)
 '(cua-mode t nil (cua-base))
 '(grep-find-template "grep <C> -nRH -e <R> <D> | grep -v .git")
 '(js-indent-level 2)
 '(show-paren-mode t)
 '(tool-bar-mode nil))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#000000" :foreground "#b0b0b0" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
 '(compilation-error ((t (:underline "#dc322f" :bold t))))
 '(compilation-info ((t (:inherit (quote font-lock-string-face) :bold t))))
 '(compilation-line-number ((t (:foreground "#cb4b16" :bold t))))
 '(completion-dynamic-face ((t (:inherit (quote match)))))
 '(cursor ((t (:background "#b58900" :foreground "#000000"))))
 '(diff-added ((t (:foreground "#859900"))))
 '(diff-changed ((t (:foreground "#b58900"))))
 '(diff-context ((t (:foreground "#586e75"))))
 '(diff-indicator-added ((t (:foreground "#859900" :background "#002029"))))
 '(diff-indicator-chnaged ((t (:foreground "#b58900" :background "#002029"))))
 '(diff-indicator-removed ((t (:foreground "#dc322f" :background "#002029"))))
 '(diff-removed ((t (:foreground "#dc322f"))))
 '(erb-comment-delim-face ((t (:inherit (quote font-lock-comment-delimiter-face)))))
 '(erb-comment-face ((t (:inherit (quote font-lock-comment-face)))))
 '(erb-delim-face ((t (:foreground "#586e75"))))
 '(erb-face ((t (:inherit (quote default)))))
 '(erb-out-delim-face ((t (:foreground "#268bd2"))))
 '(erb-out-face ((t (:inherit (quote default)))))
 '(flymake-errline ((t :underline "#dc322f")))
 '(flymake-warnline ((t :underline "#b58900")))
 '(flyspell-duplicate ((t (:underline "#b58900"))))
 '(flyspell-incorrect ((t (:underline "#dc322f"))))
 '(font-latex-sectioning-0-face ((t (:inherit (quote outline-1) :height 1.0))))
 '(font-latex-sectioning-1-face ((t (:inherit (quote font-latex-sectioning-0-face)))))
 '(font-latex-sectioning-2-face ((t (:inherit (quote font-latex-sectioning-0-face)))))
 '(font-latex-sectioning-3-face ((t (:inherit (quote font-latex-sectioning-0-face)))))
 '(font-latex-sectioning-4-face ((t (:inherit (quote font-latex-sectioning-0-face)))))
 '(font-latex-sectioning-5-face ((t (:inherit (quote font-latex-sectioning-0-face)))))
 '(font-lock-builtin-face ((t (:foreground "#586e75"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#657b83" :bold t))))
 '(font-lock-comment-face ((t (:foreground "#4a4a4a" :slant italic :weight normal))))
 '(font-lock-constant-face ((t (:foreground "#b58900"))))
 '(font-lock-function-name-face ((t (:foreground "#f64c57" :underline t :weight bold))))
 '(font-lock-keyword-face ((t (:background "#222222" :foreground "#915fd8" :weight extra-light))))
 '(font-lock-negation-char-face ((t (:inverse-video t))))
 '(font-lock-preprocessor-face ((t (:foreground "#dc322f"))))
 '(font-lock-string-face ((t (:background "#1a1a1a" :foreground "#7DD1BE"))))
 '(font-lock-type-face ((t (:foreground "#F772F3" :slant italic :weight normal))))
 '(font-lock-variable-name-face ((t (:foreground "#d33682"))))
 '(font-lock-warning-face ((t (:underline "#dc322f"))))
 '(fringe ((t (:background "#002029" :foreground "#586e75"))))
 '(highlight ((t (:background "#002029"))))
 '(hl-line ((t (:background "#002029"))))
 '(ido-first-match ((t (:foreground "#b58900" :biold true))))
 '(ido-subdir ((t (:inherit (quote font-lock-function-name-face)))))
 '(isearch ((t (:background "#d33682" :foreground "#fdf6e3"))))
 '(lazy-highlight ((t (:background "#fdf6e3" :foreground "#657b83"))))
 '(link ((t (:underline "#2aa198"))))
 '(magit-branch ((t (:inherit (quote font-lock-comment-face)))))
 '(magit-diff-add ((t (:inherit (quote diff-added)))))
 '(magit-diff-del ((t (:inherit (quote diff-removed)))))
 '(magit-diff-file-header ((t (:inherit (quote font-lock-constant-face)))))
 '(magit-diff-hunk-header ((t (:inherit (quote font-lock-keyword-face)))))
 '(magit-diff-none ((t (:inherit (quote font-lock-comment-delimiter-face)))))
 '(magit-header ((t (:inherit (quote outline-1)))))
 '(magit-item-highlight ((t (:background "#002029"))))
 '(match ((t (:background "#083d4a" :foreground "#bbbbbb"))))
 '(message-header-subject ((t (:inherit (quote default) :bold t))))
 '(minibuffer-noticeable-prompt ((t (:inherit (quote font-lock-builtin-face) :bold t))))
 '(mode-line ((t (:background "#b58900" :foreground "#000000" :box (:line-width 1 :style released-button)))))
 '(mode-line-inactive ((t (:background "#333333" :foreground "#bbbbbb" :box (:line-width 1 :style released-button)))))
 '(modeline-mousable ((t (:background "#083d4a" :foreground "#bbbbbb"))))
 '(modeline-mousable-minor-mode ((t (:background "#083d4a" :foreground "#083d4a"))))
 '(nxml-attribute-local-name-face ((t (:inherit (quote font-lock-constant-face)))))
 '(nxml-attribute-value-delimiter-face ((t (:inherit (quote font-lock-string-face)))))
 '(nxml-attribute-value-face ((t (:inherit (quote font-lock-string-face)))))
 '(nxml-cdata-section-content-face ((t (:inherit (quote font-lock-string-face)))))
 '(nxml-comment-content-face ((t (:inherit (quote font-lock-comment-face)))))
 '(nxml-comment-delimiter-face ((t (:inherit (quote font-lock-comment-delimiter-face)))))
 '(nxml-element-colon-face ((t (:inherit (quote font-lock-type-face)))))
 '(nxml-element-local-name-face ((t (:inherit (quote font-lock-function-name-face)))))
 '(nxml-element-prefix-face ((t (:inherit (quote font-lock-keyword-face)))))
 '(nxml-entity-ref-name-face ((t (:inherit (quote font-lock-constant-face)))))
 '(nxml-tag-delimiter-face ((t (:inherit (quote font-lock-function-name-face)))))
 '(nxml-tag-slash-face ((t (:inherit (quote font-lock-function-name-face)))))
 '(org-agenda-clocking ((t (:background "#003340"))))
 '(org-agenda-date ((t (:inherit (quote outline-1)))))
 '(org-agenda-date-weekend ((t (:inherit (quote outline-1)))))
 '(org-agenda-structure ((t (:foreground "#6c71c4"))))
 '(org-archived ((t (:inherit (quote font-lock-string-face)))))
 '(org-checkbox ((t (:inherit (quote mode-line) :background "#859900"))))
 '(org-column ((t (:background "#083d4a"))))
 '(org-column-title ((t (:inherit (quote mode-line) :background "#cb4b16"))))
 '(org-date ((t (:foreground "#586e75"))))
 '(org-document-info-keyword ((t (:inherit (quote font-lock-keyword-face)))))
 '(org-document-title ((t (:inherit (quote font-lock-comment-delimiter-face)))))
 '(org-done ((t (:inherit (quote mode-line) :background "#859900"))))
 '(org-hide ((t (:foreground "#003340"))))
 '(org-level-1 ((t (:inherit (quote outline-1)))))
 '(org-level-2 ((t (:inherit (quote outline-2)))))
 '(org-level-3 ((t (:inherit (quote outline-3)))))
 '(org-level-4 ((t (:inherit (quote outline-4)))))
 '(org-level-5 ((t (:inherit (quote outline-5)))))
 '(org-link ((t (:inherit (quote link)))))
 '(org-meta-line ((t (:inherit (quote font-lock-constant-face)))))
 '(org-scheduled-previously ((t (:inherit (quote font-lock-warning-face)))))
 '(org-scheduled-today ((t (:inherit (quote font-lock-comment-face)))))
 '(org-tag ((t (:foreground "#586e75"))))
 '(org-tag-default ((t (:inherit (quote org-tag)))))
 '(org-todo ((t (:inherit (quote mode-line) :background "#dc322f"))))
 '(org-upcoming-deadline ((t (:inherit (quote font-lock-string-face)))))
 '(org-warning ((t (:inherit (quote font-lock-warning-face)))))
 '(outline-1 ((t (:foreground "#cb4b16" :bold t))))
 '(outline-2 ((t (:foreground "#d33682" :bold t))))
 '(outline-3 ((t (:foreground "#268bd2" :bold nil))))
 '(outline-4 ((t (:foreground "#859900" :bold nil))))
 '(outline-5 ((t (:foreground "#dc322f" :bold nil))))
 '(rcirc-my-nick ((t (:foreground "#6c71c4"))))
 '(rcirc-server ((t (:foreground "#93a1a1"))))
 '(rcirc-timestamp ((t (:inherit (quote rcirc-server)))))
 '(rcirc-track-keyword ((t (:inherit (quote rcirc-track-nick)))))
 '(rcirc-track-nick ((t (:foreground "#586e75" :bold t))))
 '(rcirc-url ((t (:inherit (quote link)))))
 '(region ((t (:background "#083d4a"))))
 '(show-paren-match ((t (:background "#fdf6e3" :foreground "#268bd2" :bold t))))
 '(ugly-fixme-face ((t (:background "#fdf6e3" :foreground "#dc322f" :bold t :box (:line-width 1 :color "#002029")))) t)
 '(ugly-org-next-face ((t (:inherit (quote mode-line) :background "#2aa198"))) t)
 '(ugly-org-pending-face ((t (:inherit (quote mode-line) :background "#cb4b16"))) t)
 '(ugly-org-reading-face ((t (:inherit (quote mode-line) :background "#6c71c4"))) t))
